apiVersion: v2
name: ntfy
description: Helm chart for ntfy
icon: https://github.com/binwiederhier/ntfy/blob/main/web/public/static/images/ntfy.png
home: https://ntfy.sh
sources:
  - https://github.com/binwiederhier/ntfy
type: application
version: 0.9.1
appVersion: "v2.17.0"
