apiVersion: v2
name: mautrix-whatsapp
description: Helm chart for mautrix-whatsapp
home: https://docs.mau.fi/bridges/go/whatsapp/
sources:
  - https://github.com/mautrix/whatsapp
type: application
version: 0.1.1
appVersion: "v0.2602.0"
