#      .
#     / V\
#   / `  /
#  <<   |    Absolute minimal values example file for matrix-appservice-irc.
#  /    |    Set host/domain. Tokens auto-generate if omitted.
#

host: irc-media.example.com

homeserver:
  # Keep this explicit in minimal values because this is often customized.
  url: http://ess-synapse.ess.svc.cluster.local:8008
  # Required Matrix homeserver domain.
  domain: matrix.example.com
