#      .
#     / V\
#   / `  /
#  <<   |    Matrix example with recommended config for matrix-appservice-irc.
#  /    |    Ensure `domain` is your MXID `server-name` i.e. `matrix.org`.
#

host: irc-media.example.com

homeserver:
  # You can leave this as-is if you installed ESS into the `ess` namespace.
  # Otherwise, update the URL to point to your Synapse instance.
  url: http://ess-synapse.ess.svc.cluster.local:8008
  domain: matrix.example.com

registration:
  # Set if Synapse runs in a different namespace than this release.
  synapseNamespace: ess

# You can append any upstream bridge settings here.
# See: https://github.com/matrix-org/matrix-appservice-irc/blob/develop/config.sample.yaml
config:
  extra: |
    ircService:
      servers:
        irc.w3.org:
          name: W3C IRC
          port: 6679
          ssl: true
          botConfig:
            enabled: true
            nick: ess-comm-ex
          matrixClients:
            userTemplate: "@irc_$SERVER_$NICK"
            displayName: "$NICK"
          dynamicChannels:
            enabled: true
            published: false
            createAlias: true
            joinRule: public
            federate: true
    # logging:
    #   level: info
