{{- if .Values.ingress.enabled }}
{{- $host := required "values.host is required (example: irc-media.example.com)" .Values.host -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "matrix-appservice-irc.ingressName" . }}
  labels:
    {{- include "matrix-appservice-irc.componentLabels" (dict "context" . "component" "bridge") | nindent 4 }}
  {{- if .Values.ingress.clusterIssuer }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer | quote }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "matrix-appservice-irc.fullname" . }}
                port:
                  number: {{ .Values.service.mediaProxyPort }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ $host }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
{{- end }}
