{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-appservice-irc.postgresFullname" . }}
  labels:
    {{- include "matrix-appservice-irc.componentLabels" (dict "context" . "component" "postgres") | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_DB: {{ include "matrix-appservice-irc.databasePostgresDatabase" . | quote }}
  POSTGRES_USER: {{ include "matrix-appservice-irc.databasePostgresUser" . | quote }}
  POSTGRES_PASSWORD: {{ include "matrix-appservice-irc.databasePostgresPassword" . | quote }}
{{- end }}
