{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "matrix-appservice-irc.redisFullname" . }}
  labels:
    {{- include "matrix-appservice-irc.componentLabels" (dict "context" . "component" "redis") | nindent 4 }}
spec:
  serviceName: {{ include "matrix-appservice-irc.redisFullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "matrix-appservice-irc.componentSelectorLabels" (dict "context" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "matrix-appservice-irc.componentSelectorLabels" (dict "context" . "component" "redis") | nindent 8 }}
    spec:
      {{- if .Values.redis.podSecurityContext.enabled }}
      {{- $podSecurityContext := omit .Values.redis.podSecurityContext "enabled" }}
      {{- with $podSecurityContext.seccompProfile }}
      {{- if ne .type "Localhost" }}
      {{- $podSecurityContext = merge (omit $podSecurityContext "seccompProfile") (dict "seccompProfile" (omit . "localhostProfile")) }}
      {{- end }}
      {{- end }}
      securityContext:
        {{- toYaml $podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: redis
          image: {{ include "matrix-appservice-irc.redisImage" . }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          {{- if .Values.redis.securityContext.enabled }}
          securityContext:
            {{- toYaml (omit .Values.redis.securityContext "enabled") | nindent 12 }}
          {{- end }}
          args:
            {{- toYaml .Values.redis.args | nindent 12 }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
          {{- with .Values.redis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      {{- if not .Values.redis.persistence.enabled }}
      volumes:
        - name: redis-data
          emptyDir: {}
      {{- end }}
  {{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - {{ .Values.redis.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
        {{- if .Values.redis.persistence.storageClassName }}
        storageClassName: {{ .Values.redis.persistence.storageClassName }}
        {{- end }}
  {{- end }}
{{- end }}
