{{- if and (eq (.Values.registration.existingSecret | default "") "") .Values.registration.managedSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "matrix-appservice-irc.registrationTokenSecretName" . }}
  labels:
    {{- include "matrix-appservice-irc.componentLabels" (dict "context" . "component" "registration") | nindent 4 }}
type: Opaque
stringData:
  asToken: {{ include "matrix-appservice-irc.registrationAsToken" . | quote }}
  hsToken: {{ include "matrix-appservice-irc.registrationHsToken" . | quote }}
{{- end }}
