{{- if .Values.registration.createSynapseConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-appservice-irc.registrationConfigMapName" . }}
  namespace: {{ include "matrix-appservice-irc.synapseNamespace" . }}
  labels:
    {{- include "matrix-appservice-irc.componentLabels" (dict "context" . "component" "registration") | nindent 4 }}
data:
  appservice-registration-irc.yaml: |
{{ include "matrix-appservice-irc.registrationConfig" . | indent 4 }}
{{- end }}
