{{- $synapseNamespace := .Values.registration.synapseNamespace | default "" | trim -}}
{{- if and $synapseNamespace (ne $synapseNamespace .Release.Namespace) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "matrix-appservice-irc.registrationConfigMapName" . }}
  namespace: {{ $synapseNamespace }}
  labels:
    {{- include "matrix-appservice-irc.componentLabels" (dict "context" . "component" "registration") | nindent 4 }}
data:
  appservice-registration-irc.yaml: |
{{ include "matrix-appservice-irc.registrationConfig" . | indent 4 }}
{{- end }}
