#      .
#     / V\
#   / `  /
#  <<   |    Absolute minimal values example file for mautrix-googlechat.
#  /    |    You should probably check `values.matrix.example.yaml`.
#

homeserver:
  domain: matrix.example.com
