{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mautrix-zulip.postgresFullname" . }}
  labels:
    {{- include "mautrix-zulip.componentLabels" (dict "context" . "component" "postgres") | nindent 4 }}
spec:
  serviceName: {{ include "mautrix-zulip.postgresFullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "mautrix-zulip.componentSelectorLabels" (dict "context" . "component" "postgres") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mautrix-zulip.componentSelectorLabels" (dict "context" . "component" "postgres") | nindent 8 }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/postgres-secret.yaml") . | sha256sum }}
    spec:
      {{- if .Values.postgres.podSecurityContext.enabled }}
      {{- $podSecurityContext := omit .Values.postgres.podSecurityContext "enabled" }}
      {{- with $podSecurityContext.seccompProfile }}
      {{- if ne .type "Localhost" }}
      {{- $podSecurityContext = merge (omit $podSecurityContext "seccompProfile") (dict "seccompProfile" (omit . "localhostProfile")) }}
      {{- end }}
      {{- end }}
      securityContext:
        {{- toYaml $podSecurityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres
          image: {{ include "mautrix-zulip.postgresImage" . }}
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          {{- if .Values.postgres.securityContext.enabled }}
          securityContext:
            {{- toYaml (omit .Values.postgres.securityContext "enabled") | nindent 12 }}
          {{- end }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.database.name | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.database.user | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "mautrix-zulip.postgresFullname" . }}
                  key: password
          ports:
            - name: postgres
              containerPort: {{ .Values.postgres.service.port }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          {{- with .Values.postgres.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if not .Values.postgres.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
  {{- if .Values.postgres.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - {{ .Values.postgres.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.postgres.persistence.size }}
        {{- if .Values.postgres.persistence.storageClassName }}
        storageClassName: {{ .Values.postgres.persistence.storageClassName }}
        {{- end }}
  {{- end }}
{{- end }}
