apiVersion: v1
kind: Service
metadata:
  name: {{ include "mautrix-zulip.fullname" . }}
  labels:
    {{- include "mautrix-zulip.componentLabels" (dict "context" . "component" "bridge") | nindent 4 }}
spec:
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
  selector:
    {{- include "mautrix-zulip.componentSelectorLabels" (dict "context" . "component" "bridge") | nindent 4 }}
  ports:
    - name: appservice
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: appservice
