#      .
#     / V\
#   / `  /
#  <<   |    External Redis/Postgres example for mautrix-linkedin.
#  /    |    Disable bundled postgres and provide explicit connection value.
#

postgres:
  enabled: false

database:
  connectionString: postgres://mautrix_linkedin:replace_me@postgres.example.com:5432/mautrix_linkedin

homeserver:
  domain: matrix.example.com
