{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mautrix-slack.postgresFullname" . }}
  labels:
    {{- include "mautrix-slack.componentLabels" (dict "context" . "component" "postgres") | nindent 4 }}
spec:
  selector:
    {{- include "mautrix-slack.componentSelectorLabels" (dict "context" . "component" "postgres") | nindent 4 }}
  ports:
    - name: postgres
      protocol: TCP
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
{{- end }}
