apiVersion: v2
name: mautrix-zulip
description: Helm chart for mautrix-zulip
home: https://docs.mau.fi/bridges/go/zulip/
sources:
  - https://github.com/mautrix/zulip
type: application
version: 0.1.1
appVersion: "v0.2511.0"
