apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mautrix-discord.registrationConfigMapName" . }}
  labels:
    {{- include "mautrix-discord.componentLabels" (dict "context" . "component" "registration") | nindent 4 }}
data:
  {{ include "mautrix-discord.registrationFileKey" . }}: |
{{ include "mautrix-discord.registrationConfig" . | indent 4 }}
