apiVersion: v2
name: mautrix-signal
description: Helm chart for mautrix-signal
home: https://docs.mau.fi/bridges/go/signal/
sources:
  - https://github.com/mautrix/signal
type: application
version: 0.1.1
appVersion: "v0.2602.1"
