#      .
#     / V\
#   / `  /
#  <<   |    External Redis/Postgres example for mautrix-signal.
#  /    |    Disable bundled postgres and provide explicit connection value.
#

postgres:
  enabled: false

database:
  connectionString: postgres://mautrix_signal:replace_me@postgres.example.com:5432/mautrix_signal

homeserver:
  domain: matrix.example.com
