#      .
#     / V\
#   / `  /
#  <<   |    Matrix example with recommended config for mautrix-telegram.
#  /    |    Ensure `domain` is your MXID `server-name` i.e. `matrix.org`.
#

homeserver:
  address: http://ess-synapse.ess.svc.cluster.local:8008
  domain: matrix.example.com

telegram:
  # See https://docs.mau.fi/bridges/general/initial-config.html#mautrix-telegram for details
  apiID: 12345678
  apiHash: replace_with_telegram_api_hash

registration:
  # Set if Synapse runs in a different namespace than this release.
  synapseNamespace: ess

config:
  extra: |
    bridge:
      permissions:
        "*": relaybot
        "@admin:example.com": admin
