apiVersion: v2
name: mautrix-meta
description: Helm chart for mautrix-meta
home: https://docs.mau.fi/bridges/go/meta/
sources:
  - https://github.com/mautrix/meta
type: application
version: 0.1.1
appVersion: "v0.2602.0"
