#      .
#     / V\
#   / `  /
#  <<   |    External Redis/Postgres example for mautrix-meta.
#  /    |    Disable bundled postgres and provide explicit connection value.
#

postgres:
  enabled: false

database:
  connectionString: postgres://mautrix_meta:replace_me@postgres.example.com:5432/mautrix_meta

homeserver:
  domain: matrix.example.com

meta:
  mode: messenger
