{{- $synapseNamespace := include "mautrix-telegram.synapseNamespace" . -}}
{{- if and .Values.registration.createSynapseConfigMap (ne $synapseNamespace .Release.Namespace) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mautrix-telegram.registrationConfigMapName" . }}
  namespace: {{ $synapseNamespace }}
  labels:
    {{- include "mautrix-telegram.componentLabels" (dict "context" . "component" "registration") | nindent 4 }}
data:
  {{ include "mautrix-telegram.registrationFileKey" . }}: |
{{ include "mautrix-telegram.registrationConfig" . | indent 4 }}
{{- end }}
