#      .
#     / V\
#   / `  /
#  <<   |    Matrix example with recommended config for ntfy.
#  /    |    See comments for details on each config option.
#

host: ntfy.example.com

config:
  extra: |
    # Allow Matrix server to publish to UnifiedPush topics
    # See UnifiedPush documentation:
    # - https://docs.ntfy.sh/config/#example-unifiedpush
    # - https://docs.ntfy.sh/config/#acl-entries-via-the-config
    auth-access:
      - "*:up*:wo"

    # Permit Matrix server to bypass rate limits
    # See Rate limiting documentation:
    # - https://docs.ntfy.sh/config/#rate-limiting
    visitor-request-limit-exempt-hosts:
      - "matrix.example.com"
    
    # Indicate that ntfy is running behind a reverse proxy
    # See Proxy documentation:
    # - https://docs.ntfy.sh/config/#behind-a-proxy-tls-etc
    behind-proxy: true
