apiVersion: v2
name: mautrix-gvoice
description: Helm chart for mautrix-gvoice
home: https://docs.mau.fi/bridges/go/gvoice/
sources:
  - https://github.com/mautrix/gvoice
type: application
version: 0.1.0
appVersion: "v25.11"
