#      .
#     / V\
#   / `  /
#  <<   |    Matrix example with recommended config for mautrix-gvoice.
#  /    |    Ensure `domain` is your MXID `server-name` i.e. `matrix.org`.
#

homeserver:
  address: http://ess-synapse.ess.svc.cluster.local:8008
  domain: matrix.example.com

registration:
  # Set if Synapse runs in a different namespace than this release.
  synapseNamespace: ess

config:
  extra: |
    bridge:
      permissions:
        "*": user
        "@admin:example.com": admin
