apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mautrix-linkedin.registrationConfigMapName" . }}
  labels:
    {{- include "mautrix-linkedin.componentLabels" (dict "context" . "component" "registration") | nindent 4 }}
data:
  {{ include "mautrix-linkedin.registrationFileKey" . }}: |
{{ include "mautrix-linkedin.registrationConfig" . | indent 4 }}
