apiVersion: v2
name: mautrix-discord
description: Helm chart for mautrix-discord
home: https://docs.mau.fi/bridges/go/discord/
sources:
  - https://github.com/mautrix/discord
type: application
version: 0.1.0
appVersion: "v0.7.6"
