#      .
#     / V\
#   / `  /
#  <<   |    External Redis/Postgres example for mautrix-twitter.
#  /    |    Disable bundled postgres and provide explicit connection value.
#

postgres:
  enabled: false

database:
  connectionString: postgres://mautrix_twitter:replace_me@postgres.example.com:5432/mautrix_twitter

homeserver:
  domain: matrix.example.com
