{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "irc-bridge.redisFullname" . }}
  labels:
    {{- include "irc-bridge.componentLabels" (dict "context" . "component" "redis") | nindent 4 }}
spec:
  serviceName: {{ include "irc-bridge.redisFullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "irc-bridge.componentSelectorLabels" (dict "context" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "irc-bridge.componentSelectorLabels" (dict "context" . "component" "redis") | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: {{ include "irc-bridge.redisImage" . }}
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          args:
            {{- toYaml .Values.redis.args | nindent 12 }}
          ports:
            - name: redis
              containerPort: {{ .Values.redis.service.port }}
          {{- with .Values.redis.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      {{- if not .Values.redis.persistence.enabled }}
      volumes:
        - name: redis-data
          emptyDir: {}
      {{- end }}
  {{- if .Values.redis.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes:
          - {{ .Values.redis.persistence.accessMode }}
        resources:
          requests:
            storage: {{ .Values.redis.persistence.size }}
        {{- if .Values.redis.persistence.storageClassName }}
        storageClassName: {{ .Values.redis.persistence.storageClassName }}
        {{- end }}
  {{- end }}
{{- end }}
