{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "irc-bridge.redisFullname" . }}
  labels:
    {{- include "irc-bridge.componentLabels" (dict "context" . "component" "redis") | nindent 4 }}
spec:
  selector:
    {{- include "irc-bridge.componentSelectorLabels" (dict "context" . "component" "redis") | nindent 4 }}
  ports:
    - name: redis
      protocol: TCP
      port: {{ .Values.redis.service.port }}
      targetPort: redis
{{- end }}
