apiVersion: v1
kind: Secret
metadata:
  name: {{ include "irc-bridge.registrationTokenSecretName" . }}
  labels:
    {{- include "irc-bridge.componentLabels" (dict "context" . "component" "registration") | nindent 4 }}
type: Opaque
stringData:
  asToken: {{ include "irc-bridge.registrationAsToken" . | quote }}
  hsToken: {{ include "irc-bridge.registrationHsToken" . | quote }}
