{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mautrix-googlechat.postgresFullname" . }}
  labels:
    {{- include "mautrix-googlechat.componentLabels" (dict "context" . "component" "postgres") | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.database.password | quote }}
{{- end }}
