apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mautrix-googlechat.registrationConfigMapName" . }}
  labels:
    {{- include "mautrix-googlechat.componentLabels" (dict "context" . "component" "registration") | nindent 4 }}
data:
  {{ include "mautrix-googlechat.registrationFileKey" . }}: |
{{ include "mautrix-googlechat.registrationConfig" . | indent 4 }}
