{{- $synapseNamespace := .Values.registration.synapseNamespace | default "" | trim -}}
{{- if and $synapseNamespace (ne $synapseNamespace .Release.Namespace) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mautrix-googlechat.registrationConfigMapName" . }}
  namespace: {{ $synapseNamespace }}
  labels:
    {{- include "mautrix-googlechat.componentLabels" (dict "context" . "component" "registration") | nindent 4 }}
data:
  {{ include "mautrix-googlechat.registrationFileKey" . }}: |
{{ include "mautrix-googlechat.registrationConfig" . | indent 4 }}
{{- end }}
